### PR TITLE
Multi gpu

### PR DESCRIPTION
**Pull request by jackie930**
this commit related to issue: https://github.com/yangheng95/PyABSA/issues/109.
mainly support multi-gpu training via pytorch dataparrel api.
the change is only currently effective for: `bert-base-atepc` task, and it's fully tested.

### CODE REVIEW

**Comment by yangheng95** [comment]
Great job! @jackie930 I guess sometimes it's not necessary to occupy all cudas, typically while the data is limited. So, I wolud like to associate the multi cuda support with `autocuda` parameter, e.g., set `autocuda=[0,1,3]` or `autocuda=allcuda`, and  os.environ['CUDA_VISIBLE_DEVICES']=','.format([autocuda]). What do you think, is there some better strategy to customize cuda assignment?

**Comment by yangheng95** [comment]
Feel free to share your advice, if you are not available for further commit, I will do it according to the discussion.

**Comment by jackie930** [comment]
i can do the revise on supporting selected cuda service maybe later this week, how about you?
btw, i will continue the work on multi-gpu training supporting for other models these days, starting by bert-spc, keep in touch!

**Comment by yangheng95** [comment]
Please follow your schedule, I will finish it (if not yet) while testing and release PyPi pakcage.

**Comment by jackie930** [comment]
> Please follow your schedule, I will finish it (if not yet) while testing and release PyPi pakcage.

no problem!

**Comment by yangheng95** [comment]
@all-contributors bot please add @jackie930 for code

**Pull request merged**
