### PR TITLE
Update dataset_list.py

### PR DESCRIPTION
**Pull request by christianjosef27**

### CODE REVIEW

**Comment by yangheng95** [comment]
Hi @christianjosef27, thanks very much for your PR! It seems this PR is related to a custom contribution, but you have not merged the dataset in ABSADatasets. Are you willing to share your dataset in [ABSADatasets](https://github.com/yangheng95/ABSADatasets)?

**Comment by christianjosef27** [comment]
Hi Yang, yes I want to train your multilingual model with my German student reviews dataset, I first tried to pass the Trainer my local directory but it didn't work. So I thought I need to insert it in the DatasetList Class. I have to check with my professor if I am allowed to share the data, for me it would be of course no problem. Is it possible for now to train my model without merging it in ABSADatasets? Greetings Christian-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 04.04.23, 19:03 schrieb Heng Yang ***@***.***>:

   
  Hi @christianjosef27, thanks very much for your PR! It seems this PR is related to a custom conribution, but you have not merge the dataset in ABSADatasets. Are you willing to share your dataset in ABSADatasets?

**Comment by yangheng95** [comment]
Seems you have problem in locating the dataset. It should be ok if you pass the dir to trainer, can you show me your code snippet for training?

**Comment by yangheng95** [comment]
In the case of your situation, it is not necessary to share your datasets.

**Comment by christianjosef27** [comment]
Yes, I have created my local folder hierarchy as described in the documentation and tried to move the files to certrain folders.

The name of the files are also like described in the doc.

 

Code snippet (the 133.universities folder contains my 3 files):


from pyabsa import DatasetItem
my_dataset = DatasetItem('Uni_Reviews', ['C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/datasets/atepc_datasets/133.universities'])

trainer = ATEPC.ATEPCTrainer(
    config=config,
    dataset=my_dataset,
    from_checkpoint="multilingual",  # if you want to resume training from our pretrained checkpoints, you can pass the checkpoint name here
    auto_device=DeviceTypeOption.AUTO,  # use cuda if available
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,  # save state dict only instead of the whole model
    path_to_save='C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Modeling/saved_trained_models',
    load_aug=False  # there are some augmentation dataset for integrated datasets, you use them by setting load_aug=True to improve performance
)





Gesendet: Dienstag, 04. April 2023 um 19:09 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

Seems you have problem in locating the dataset. It should be ok if you pass the dir to trainer, can you show me your code snippet for training?

**Comment by christianjosef27** [comment]
And my files are named as "universities.train.dat.atepc", "universities.val.dat.atepc" and "universities.test.dat.atepc".

 
 

Gesendet: Dienstag, 04. April 2023 um 19:11 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

In the case of your situation, it is not necessary to share your datasets.

**Comment by yangheng95** [comment]
As a simple solution, you can ceate a dir named with "integrated_datasets" and move the datasets dir into it.

**Comment by christianjosef27** [comment]
Okay, I tried that, still error but different one:

 


ValueError: Cannot find dataset: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/datasets/atepc_datasets/133.universities, you may need to remove existing integrated_datasets and try again. Please note that if you are using keywords to let findfile search the dataset, you need to save your dataset(s) in integrated_datasets/task_name/dataset_name 


 

Any idea what I could do to solve this error message? I am not aware that I used any kewwords to let finfile search....

What is meant by remove existing integrated_datasets and try again?


Gesendet: Dienstag, 04. April 2023 um 20:03 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

As a simple solution, you can ceate a dir named with "integrated_datasets" and move the datasets dir into it.

**Comment by yangheng95** [comment]
For example, organize your directory as: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/**integrated_datasets**/datasets/atepc_datasets/133.universities,

**Comment by christianjosef27** [comment]
Okay I organized like that. Now again the error changed to old error:

 


raise RuntimeError(
    284         'Fail to locate dataset: {}. Your dataset should be in "datasets" folder end withs ".apc" or ".atepc" or "tc". If the error persists, '
    285         "you may need rename your dataset according to {}".format(
   (...)
    288         )
    289     )
    290 if len(dataset_file["test"]) == 0:

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: ''

 

 


 
 

Gesendet: Dienstag, 04. April 2023 um 20:37 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

For example, organize your directory as: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/**integrated_datasets/**datasets/atepc_datasets/133.universities,

**Comment by christianjosef27** [comment]
But it should be fine that the data files are directly under my "133.universities" folder I guess right?

 
 

Gesendet: Dienstag, 04. April 2023 um 20:37 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

For example, organize your directory as: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/**integrated_datasets/**datasets/atepc_datasets/133.universities,

**Comment by christianjosef27** [comment]
Do you know how I could fix that? :) -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 04.04.23, 20:37 schrieb Heng Yang ***@***.***>:

   
  For example, organize your directory as: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/**integrated_datasets/**datasets/atepc_datasets/133.universities,

**Comment by christianjosef27** [comment]
Im quite new to github, could the reason why it doesnt work be that you have not verified my PR?

Because I cannot see my added code in your public repo in the ATEPCDatasetList.

 

 
 

Gesendet: Dienstag, 04. April 2023 um 20:37 Uhr
Von: "Heng Yang" ***@***.***>
An: "yangheng95/PyABSA" ***@***.***>
Cc: "christianjosef27" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [yangheng95/PyABSA] Update dataset_list.py (PR #295)


 

For example, organize your directory as: C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Excel_Dataframes_Unis/Clean Split Data/70_15_15/**integrated_datasets/**datasets/atepc_datasets/133.universities,

**Comment by yangheng95** [comment]
Since your dataset is not intended to share with community, this modification will lead to errors for other users if this PR is merged. 

Please update to the latest version, and then pass the exact dataset dir to trainer. Then it should work.

**Comment by christianjosef27** [comment]
On Github I clicked "Merge with base branch". I dont know if this is equivalent to "updae to the latest version" that you asked me to do.
Is it okay now? 

I tried again to execute the Trainer command and still same error. I am sure that my path of the dir is correct and my datasets are named like that:
image


If I cannot find a solution I will be willing to share the set in ABSA Datasets...
Because I really dont know how to solve that error.
​​​​​​​

**Comment by yangheng95** [comment]
No, you need to close this PR, and re-clone this repo and work on it. Then you can simply use the absoult path of your dataset directory in the trainer.

**Comment by christianjosef27** [comment]
Okay, closed. However, I still get same error, I pass my local absolute path to Trainer but still cant locate my files :(

from pyabsa import DatasetItem
my_dataset = DatasetItem('University', **['C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Modeling/integrated_datasets/atepc_datasets/177.University']**)


trainer = ATEPC.ATEPCTrainer(
    config=config,
    dataset=my_dataset,
    from_checkpoint="multilingual",  # if you want to resume training from our pretrained checkpoints, you can pass the checkpoint name here
    auto_device=DeviceTypeOption.AUTO,  # use cuda if available
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,  # save state dict only instead of the whole model
    path_to_save='C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Modeling/saved_trained_models',
    load_aug=False  # there are some augmentation dataset for integrated datasets, you use them by setting load_aug=True to improve performance
)

**Comment by christianjosef27** [comment]
My error is this:

image

**Comment by yangheng95** [comment]
Just let dataset="C:/Users/chris/Documents/A_Masterarbeit/Prepare Train Dataset/Modeling/integrated_datasets/atepc_datasets/177.University" in the trainer.

**Comment by yangheng95** [comment]
Remember to update pyabsa==2.2.2

**Comment by christianjosef27** [comment]
Thank you! With those 2 steps it worked and it could find my datasets. 
Only it seems sth with the config is still wrong. But I copied exactly the example from the demo.

The error seems to be I have to add some more parameters to the config?

image


image

**Comment by yangheng95** [comment]
The checkpoint is not available for all situations, please remove it

**Comment by christianjosef27** [comment]
What do you mean by "all situations"? So I cannot use mutlilingual model for fine-tuning?

**Comment by christianjosef27** [comment]
*Or is multilingual model anyway my base as i have it in the config ? (With get_atepc_config_multilingual())

**Comment by christianjosef27** [comment]
It worked with removing the checkpoint. However in the Epoch 3 I got an AttributeNotFound Error:

image

Have you encountered this error before?

**Pull request closed without merging**
